import { expect, test } from '@playwright/test'

test('prepare, export, and reopen a frozen prompt plan without claiming inference', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('API connected')).toBeVisible()
  await page.getByRole('button', { name: 'Prompt lab', exact: true }).click()
  await page.getByLabel('Prompt case').selectOption('FL-002')
  await page.getByLabel('Prompt strategy').selectOption('chain_evidence')
  const response = page.waitForResponse(response => response.url().endsWith('/api/prompt-plans') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Prepare prompt plan', exact: true }).click()
  const plan = await (await response).json()
  const preview = page.getByRole('region', { name: 'Prepared prompt plan' })
  await expect(preview).toBeVisible()
  await expect(preview.getByText('PREPARED · NO INFERENCE')).toBeVisible()
  await expect(preview.getByText('Pending previous model responses; not materialized')).toHaveCount(2)
  await expect(page.getByLabel('user prompt')).toContainText('IndexError')
  const exported = await page.request.get(await page.getByRole('link', { name: 'Export plan' }).getAttribute('href') ?? '')
  expect((await exported.json()).first_messages_sha256).toBe(plan.first_messages_sha256)
  await page.reload()
  await page.getByRole('button', { name: 'Prompt lab', exact: true }).click()
  await page.getByRole('button', { name: 'Open plan', exact: true }).first().click()
  await expect(page.getByLabel('user prompt')).toHaveText(plan.first_messages[1].content)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
