import { expect, test } from '@playwright/test'

test('run a real comparison, inspect evidence, export, and reopen after reload', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByText('API connected')).toBeVisible()
  await page.getByRole('button', { name: 'New experiment', exact: true }).first().click()
  await page.getByLabel('Experiment name').fill('Browser verified comparison')
  const queueResponse = page.waitForResponse(response => response.url().endsWith('/api/jobs') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Run experiment', exact: true }).click()
  const submitted = await (await queueResponse).json()
  await expect(page.locator(`[data-job-id="${submitted.id}"] .job-status`)).toHaveText('completed')
  await expect(page.getByRole('link', { name: 'Export JSON' })).toHaveAttribute('href', `/api/experiments/${submitted.id}/export`)
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.locator('.experiment-strip').getByText('Browser verified comparison', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /test_threshold_order/ })).toContainText('FAIL')
  await page.getByRole('button', { name: /test_threshold_order/ }).click()
  await expect(page.getByText('-1900', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Reveal known fault' }).click()
  await expect(page.getByText('Known fault: line 3')).toBeVisible()
  await page.getByRole('button', { name: 'Tarantula', exact: true }).click()
  await expect(page.getByText('Tarantula · rank of the known fault')).toBeVisible()
  await page.getByRole('button', { name: /Line 3/ }).click()
  await expect(page.locator('#line-3')).toHaveClass(/focused/)
  const response = await page.request.get(await page.getByRole('link', { name: 'Export JSON' }).getAttribute('href') ?? '')
  expect(response.status()).toBe(200)
  const exported = await response.json()
  expect(exported.results).toHaveLength(12)
  expect(exported.results[0].tests.some((test: { passed: boolean }) => !test.passed)).toBe(true)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: '../docs/screenshots/workbench.png', fullPage: true })
  await page.getByRole('button', { name: /Experiments/ }).click()
  await expect(page.getByRole('cell', { name: /Browser verified comparison/ }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Open', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'The debugging workbench' })).toBeVisible()
  await page.reload()
  await expect(page.locator('.experiment-strip').getByText('Browser verified comparison', { exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('search, selection validation, and methodology work on a mobile viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByText('API connected')).toBeVisible()
  await page.keyboard.press('/')
  await expect(page.getByRole('textbox', { name: 'Search bugs' })).toBeFocused()
  await page.getByRole('textbox', { name: 'Search bugs' }).fill('median')
  await expect(page.locator('.bug-item')).toHaveCount(1)
  await page.getByRole('button', { name: /Even-length median/ }).click()
  await expect(page.getByRole('heading', { name: 'Even-length median shifts one position' })).toBeVisible()
  await page.getByRole('button', { name: /test_two_values/ }).click()
  await expect(page.getByText('IndexError: list index out of range')).toBeVisible()
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
  expect(overflow).toBe(false)
  await page.screenshot({ path: '../docs/screenshots/mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'New experiment', exact: true }).first().click()
  await page.getByRole('button', { name: 'Clear', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Run experiment', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Close experiment dialog' }).click()
  await page.getByRole('button', { name: 'Methodology', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Know what you’re measuring.' })).toBeVisible()
  await expect(page.getByText('No live LLM runs or AI accuracy claims in this release.')).toBeVisible()
})
